new manubot yaml

diff --git a/.github/workflows/manubot.yaml b/.github/workflows/manubot.yaml
--- a/.github/workflows/manubot.yaml
+++ b/.github/workflows/manubot.yaml
@@ -3,11 +3,9 @@ on:
   push:
     branches:
       - main
-      - master
   pull_request:
     branches:
       - main
-      - master
   # NOTE: scheduled workflows aren't supported
   # https://github.community/t/github-event-repository-fork-context-does-detect-forks-in-scheduled-jobs/185925
   workflow_dispatch:
@@ -19,7 +17,7 @@ on:
       BUILD_DOCX:
         type: boolean
         description: generate DOCX output
-        default: true
+        default: false
       BUILD_LATEX:
         type: boolean
         description: generate LaTeX output
@@ -33,13 +31,20 @@ on:
         description: Use Docker to generate PDF
         default: true
 
+concurrency:
+  # only one run per branch at a time
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   manubot:
     name: Manubot
     runs-on: ubuntu-latest
     permissions:
       contents: write
+      pull-requests: write
     env:
+      BUILD_DOCX: true
       GITHUB_PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
       # Set SPELLCHECK to true/false for whether to check spelling in this action.
       # For workflow dispatch jobs, this SPELLCHECK setting will be overridden by the user input.
@@ -49,7 +54,7 @@ jobs:
         shell: bash --login {0}
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           # fetch entire commit history to support get_rootstock_commit
           fetch-depth: 0
@@ -71,28 +76,29 @@ jobs:
           echo "DEFAULT_BRANCH_REF=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_ENV
           echo "DEFAULT_BRANCH=$DEFAULT_BRANCH"
       - name: Cache
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: ci/cache
           key: ci-cache-${{ github.ref }}
           restore-keys: |
             ci-cache-${{ env.DEFAULT_BRANCH_REF }}
       - name: Install Environment
-        uses: conda-incubator/setup-miniconda@v2
+        uses: conda-incubator/setup-miniconda@v3
         with:
           activate-environment: manubot
           environment-file: build/environment.yml
           auto-activate-base: false
           miniforge-variant: Mambaforge
-          miniforge-version: 'latest'
+          miniforge-version: "latest"
           use-mamba: true
       - name: Install Spellcheck
         if: env.SPELLCHECK == 'true'
         run: bash ci/install-spellcheck.sh
       - name: Build Manuscript
-        run: BUILD_DOCX=true bash build/build.sh
+        run: bash build/build.sh
       - name: Upload Artifacts
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
+        id: artifact-upload-step
         with:
           name: manuscript-${{ github.run_id }}-${{ env.TRIGGERING_SHA_7 }}
           path: output
@@ -104,3 +110,34 @@ jobs:
           CI_BUILD_WEB_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
           CI_JOB_WEB_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
         run: bash ci/deploy.sh
+      - name: Count spelling errors
+        run: |
+          # count the number of spelling errors using the spelling-error-locations.txt file
+          # this file does not include preamble or author list spelling errors
+          if [ -s output/spelling-error-locations.txt ]; then
+            echo "SPELLING_ERRORS=$(wc -l < output/spelling-error-locations.txt)" >> $GITHUB_ENV
+          else
+            echo "SPELLING_ERRORS=0" >> $GITHUB_ENV
+          fi
+      - name: Post artifact comment to PR
+        if: github.event_name == 'pull_request'
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            **Click the link below to download the manuscript build as a ZIP file.**
+            This build is associated with commit ${{ env.TRIGGERING_SHA_7 }}.
+
+            [Manuscript build](${{ steps.artifact-upload-step.outputs.artifact-url }})
+
+            **There were ${{ env.SPELLING_ERRORS }} spelling errors.**
+            Check the build link above for details.
+
+      - name: Fail for spelling errors in manual builds
+        if: github.event_name == 'workflow_dispatch' && env.SPELLCHECK == 'true'
+        run: |
+          if [ $SPELLING_ERRORS ]; then
+            echo "Spelling errors (some may be in the author list):"
+            cat output/spelling-errors.txt
+            exit 1
+          fi
